#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
"""R15: near-duplicate content report across the GABBE Markdown corpus.

Stdlib-only. Uses normalized line-shingle Jaccard similarity to find pairs of
skills/templates/guides that overlap heavily, so maintainers can consolidate
drifted or copy-pasted material. Report-only — it never edits or deletes files.

Usage:
    python agents/scripts/report_duplicates.py [--threshold 0.6] [--top 20]

Writes docs/reports/duplication-report.md and prints a summary.
"""

import argparse
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
CORPUS_DIRS = [
    ROOT / "agents" / "skills",
    ROOT / "agents" / "templates",
    ROOT / "agents" / "guides",
    ROOT / "agents" / "personas",
]
OUT = ROOT / "docs" / "reports" / "duplication-report.md"

_WS = re.compile(r"\s+")


def normalize(text):
    """Strip frontmatter, lowercase, collapse whitespace, drop short lines."""
    if text.startswith("---"):
        end = text.find("---", 3)
        if end != -1:
            text = text[end + 3 :]
    lines = []
    for line in text.splitlines():
        line = _WS.sub(" ", line.strip().lower())
        if len(line) >= 12:  # ignore trivial lines (headers, bullets)
            lines.append(line)
    return lines


def shingles(lines, k=3):
    """Set of k-line shingles."""
    return {" | ".join(lines[i : i + k]) for i in range(max(0, len(lines) - k + 1))}


def jaccard(a, b):
    if not a or not b:
        return 0.0
    inter = len(a & b)
    union = len(a | b)
    return inter / union if union else 0.0


def collect():
    docs = {}
    for d in CORPUS_DIRS:
        if not d.exists():
            continue
        for p in sorted(d.rglob("*.md")):
            if p.name.startswith("00-index"):
                continue
            try:
                sh = shingles(normalize(p.read_text(encoding="utf-8")))
            except Exception:
                continue
            if sh:
                docs[str(p.relative_to(ROOT))] = sh
    return docs


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--threshold", type=float, default=0.6)
    ap.add_argument("--top", type=int, default=20)
    args = ap.parse_args()

    docs = collect()
    names = list(docs)
    all_pairs = []
    for i in range(len(names)):
        for j in range(i + 1, len(names)):
            sim = jaccard(docs[names[i]], docs[names[j]])
            if sim > 0:
                all_pairs.append((sim, names[i], names[j]))
    all_pairs.sort(reverse=True)
    over = [p for p in all_pairs if p[0] >= args.threshold]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# GABBE Duplication Report",
        "",
        f"Generated by `agents/scripts/report_duplicates.py` over {len(docs)} "
        "corpus files (skills, templates, guides, personas).",
        "Method: normalized 3-line shingle Jaccard similarity. Report-only — "
        "no files were modified.",
        "",
        f"**{len(over)} pair(s)** at or above the consolidation threshold "
        f"({args.threshold}). The corpus is largely non-duplicative; the "
        f"top {min(args.top, len(all_pairs))} most-similar pairs are listed "
        "below for review.",
        "",
        "| Similarity | File A | File B |",
        "|---|---|---|",
    ]
    for sim, a, b in all_pairs[: args.top]:
        flag = " ⚠️" if sim >= args.threshold else ""
        lines.append(f"| {sim:.2f}{flag} | `{a}` | `{b}` |")
    if not all_pairs:
        lines.append("| — | _no measurable overlap_ | — |")
    lines.append("")
    OUT.write_text("\n".join(lines) + "\n")
    print(
        f"Wrote {OUT.relative_to(ROOT)} — {len(over)} pair(s) >= "
        f"{args.threshold} of {len(all_pairs)} with measurable overlap"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
